---
services:
  aicovergen:
    build:
      context: .
      dockerfile: Dockerfile_amd
    container_name: aicovergen
    volumes:
      - ./mdxnet_models:/app/mdxnet_models
      - ./rvc_models:/app/rvc_models
      - ./song_output:/app/song_output
    ports:
      - "7860:7860"
    security_opt:
      - seccomp=unconfined # recommended for performance
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - TZ=Europe/Kyiv
      - HCC_AMDGPU_TARGET=gfx1031       # name of your GPU, not your graphics card. My card is a 6650XT, so the GPU is a gfx1031.
      - HSA_OVERRIDE_GFX_VERSION=10.3.0 # version of CUDA you're trying to run 
                                        # (The 10.3.0 comes from gfx1031, its the nearest supported.)
                                        # (not supported) 10.3.1 -> (supported) 10.3.0.

