---
services:
  aicovergen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aicovergen
    volumes:
      - ./mdxnet_models:/app/mdxnet_models
      - ./rvc_models:/app/rvc_models
      - ./song_output:/app/song_output
    ports:
      - "7860:7860"
    security_opt:
      - seccomp=unconfined # recommended for performance
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - HCC_AMDGPU_TARGET=gfx1030         # (optional for officialy unsupported GPUs)
      - HSA_OVERRIDE_GFX_VERSION=10.3.0   # set accordicg to your GPU

