---
services:
  aicovergen_amd:
    image: aicovergen_amd
    container_name: aicovergen_amd
    volumes:
      - ../mdxnet_models:/app/mdxnet_models
      - ../rvc_models:/app/rvc_models
      - ../song_output:/app/song_output
    ports:
      - "7860:7860"
    security_opt:
      - seccomp=unconfined # recommended for performance
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - TZ=Europe/Kyiv
      - HCC_AMDGPU_TARGET=gfx1031       # name of your GPU, not your graphics card. My card is a 6650XT, so the GPU is a gfx1031.
      - HSA_OVERRIDE_GFX_VERSION=10.3.0 # version of CUDA you're trying to run 
                                        # (The 10.3.0 comes from gfx1031, its the nearest supported.)
                                        # (not supported) 10.3.1 -> (supported) 10.3.0.
      # (optional) Might be requierd if multiple AMD GPUs are present
      # - PYTORCH_ROCM_ARCH="gfx1030"     # compile PyTorch only for your microarchitecture (uarch)
      # - export ROCR_VISIBLE_DEVICES=0
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 # Fix memmory leak (HIP out of memory error)