---
services:
  aicovergen_nvidia:
    build:
      context: ../
      dockerfile: docker/Dockerfile_nvidia
    image: aicovergen_nvidia
    container_name: aicovergen_nvidia
    volumes:
      - ../mdxnet_models:/app/mdxnet_models
      - ../rvc_models:/app/rvc_models
      - ../song_output:/app/song_output
    ports:
      - "7860:7860"
    environment:
      - TZ=Europe/Kyiv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]