---
services:
  aicovergen_nvidia:
    image: aicovergen_nvidia
    container_name: aicovergen_nvidia
    volumes:
      - ../mdxnet_models:/app/mdxnet_models
      - ../rvc_models:/app/rvc_models
      - ../song_output:/app/song_output
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Los_Angeles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]